# Generated by Django 5.2.12 on 2026-08-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_tag_birthday_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congratulation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='congratulation',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='tags',
        ),
        migrations.RemoveConstraint(
            model_name='birthday',
            name='unique_birthday_person',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='author',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='image',
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.DeleteModel(
            name='Congratulation',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
